#!/bin/sh
module="scull2"
device="scull2"
mode="666"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
sudo insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms
sudo rm -f /dev/${device}0
sudo mknod /dev/${device}0 c $major 0
sudo chgrp $group /dev/${device}0 
sudo chmod $mode  /dev/${device}0
