#!/bin/bash

function make_minors {
    let part=1
    while (($part < $minors)); do
	let minor=$part
	sudo mknod $1$part b $major $minor
	let part=$part+1
    done
}


# FIXME: This isn't handling minors (partitions) at all.
module="sbull"
device="sbull"
mode="666"
chardevice="sbullr"
minors=1

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
sudo /sbin/insmod -f ./$module.ko $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Remove stale nodes and replace them, then give gid and perms

sudo rm -f /dev/${device}a /dev/${device}

sudo mknod /dev/${device}a b $major 0
make_minors /dev/${device}a
sudo chgrp $group /dev/${device}a*
sudo chmod $mode  /dev/${device}a*
